config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :todos do
    member do
      patch 'move'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'todos#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# :nodoc:
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
# frozen_string_literal: true

# Model class from generator.
class Todo < ApplicationRecord
  validates :name, presence: true

  # From the 'positioned' gem
  positioned
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# :nodoc:
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  before_action :set_todo, only: %i[show edit update destroy move]

  def index
    @todos = Todo.order(:position)
  end

  def show; end

  def new
    @todo = Todo.new
  end

  def edit; end

  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.json { render :show, status: :created, location: @todo }
      else
        format.turbo_stream { render 'errors' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      attributes = todo_params
      if @todo.update(attributes)
        format.turbo_stream
        format.json { render :show, status: :ok, location: @todo }
      else
        format.turbo_stream { render 'errors' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo.destroy!

    respond_to do |format|
      format.turbo_stream
      format.json { head :no_content }
    end
  end

  def move
    @todo.update(position: params[:position])
    head :no_content
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :description, :position)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# :nodoc:
module ApplicationHelper
  def model_title(model, attribute_name, default: nil)
    title = model.try(attribute_name)
    return title if title.present?

    default || "#{model.model_name.human} ##{model.id}"
  end

  def model_value(model, attribute_name, default: '---')
    value = model.try(attribute_name)

    value.presence || default
  end

  def model_date_value(model, attribute_name, default: '---')
    value = model.try(attribute_name)

    value.present? ? I18n.l(value, format: :template_date) : default
  end

  def model_datetime_value(model, attribute_name, default: '---')
    value = model.try(attribute_name)

    value.present? ? I18n.l(value, format: :template_datetime) : default
  end
  alias model_timestamp_value model_datetime_value

  def model_time_value(model, attribute_name, default: '---')
    value = model.try(attribute_name)

    value.present? ? I18n.l(value, format: :template_time) : default
  end

  def default_image_tag(image, variant: nil)
    file = variant ? image.variant(variant) : image
    filename = file.filename.sanitized
    image_tag file, alt: filename, title: filename
  end
end

app/helpers/todos_helper.rb
# frozen_string_literal: true

module TodosHelper
end

app/views/application/_errors.html.slim
- # locals: (message:, todo:)

div class="errors-explanation" data-controller="alerts" data-alerts-target="alert"
  div class="flex flex-row"
    div class="grow"
      h2 = message
      ul class="list-disc"
        - todo.errors.each do |error|
          li = error.full_message
    div
      a class="cursor-pointer" data-action="click->alerts#close"
        svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 hover:scale-125"
          path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"

app/views/application/_notification.html.slim
- # locals: (message:)

div id="notification" data-controller="alerts" data-alerts-target="alert"
  div class="flex flex-row"
    div class="grow"
      = message
    div
      a class="cursor-pointer" data-action="click->alerts#close"
        svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 hover:scale-125"
          path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"

app/views/application/_notifications.html.slim
- # locals: (message:)

div id="notification" data-controller="notifications" data-notifications-target="notifications"
  div class="flex flex-row"
    div class="grow"
      = message
    div
      a class="cursor-pointer" data-action="click->notifications#close"
        svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 hover:scale-125"
          path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for :page_title
    meta name="viewport" content="width=device-width,initial-scale=1"

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'

    = javascript_importmap_tags

  body class="container h-[calc(100%-0.5rem)] mx-auto p-1"
    main class="min-h-full w-full my-[0.25rem]"
      #alerts
      = yield

app/views/todos/_delete_link.html.slim
- #locals: (todo:)

div data-controller="dialog"
  dialog id="delete-#{dom_id todo}" data-dialog-target="dialog"
    div class="content-box mt-0 p-3 rounded-2xl"
      p class="text-lg font-bold mb-6"
        | Are you sure you want to delete this todo?
      div
        = button_to 'Delete', url_for(todo), method: :delete, title: 'Delete', class: 'btn-important w-full'
        button class="button w-full mt-2" data-action="click->dialog#close" Cancel

  button class="btn-important py-2 px-2 inline-flex items-center" data-action="click->dialog#open" title="Delete"
    svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-1"
      path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
    span Delete

app/views/todos/_form.html.slim
- # locals: (todo:, cancel_button: nil)

div class="content-box rounded-2xl"
  div id="errors-#{dom_id todo}"
  = form_with(model: todo, class: 'contents') do |form|
    div class="min-h-32 lg:flex lg:flex-row lg:gap-4 mt-4 mb-3"
      div class="lg:grow"
        div class="mb-3"
          = form.text_field :name, class: 'w-full'
          - if error = todo.errors[:name]&.first
            p class="field-error-explanation" = error.capitalize
        div class="mt-3"
          = form.text_area :description, class: 'w-full', rows: 3
          - if error = todo.errors[:description]&.first
            p class="field-error-explanation" = error.capitalize

      div class="m-0 mt-4 p-0 pt-3 lg:mt-0 lg:pt-0 flex flex-row lg:flex-col"
        div class="grow"
          = render 'form_save', form:
        div
          - if cancel_button
            = cancel_button
          - else
            = render 'form_cancel', form:

app/views/todos/_form_cancel.html.slim
- # locals: (form:)

= link_to form.object, title: 'Cancel', class: 'button py-2 px-2 inline-flex items-center' do
  svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
    path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"
  span Cancel

app/views/todos/_form_save.html.slim
- # locals: (form:)

= form.button title: 'Save', class: 'btn-action py-2 px-2 inline-flex items-center' do
  svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-1"
    path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5"
  span Save

app/views/todos/_spacer.html.slim
div class="list-spacer"

app/views/todos/_todo.html.slim
- # locals: (todo:)

= turbo_frame_tag todo, class: 'w-full', data: { id: todo.id } do
  div id="#{dom_id todo}" class="content-box relative rounded-2xl"
    div class="handle"
      svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-8 w-8 mx-auto"
        path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"

    div class="min-h-32 lg:flex lg:flex-row lg:gap-2 mt-4 mb-3"
      div class="lg:grow"
        div class="text-2xl font-bold"
          = model_title(todo, 'name')
        div class="my-3"
          = model_value(todo, 'description')

      div class="m-0 mt-4 p-0 pt-3 lg:mt-0 lg:pt-0 flex flex-row lg:flex-col"
        div class="grow"
          = render 'edit_link', todo:

        = render 'delete_link', todo:

app/views/todos/cancel_edit.turbo_stream.slim
= turbo_stream.replace @todo

app/views/todos/create.turbo_stream.slim
= turbo_stream.append 'todos', @todo
= turbo_stream.update 'alerts', partial: 'application/notification', locals: { message: 'New Todo added at the end of the list.' }
= turbo_stream.replace 'new_todo_link', partial: 'todos/new_todo_link'

app/views/todos/destroy.turbo_stream.slim
= turbo_stream.remove @todo
= turbo_stream.update 'alerts', partial: 'application/notification', locals: { message: 'Todo removed.' }

app/views/todos/edit.html.slim
- content_title = 'Edit todo'
- content_for :page_title, "Todos | #{content_title}"

div class="w-full"
  div class="header lg:flex items-center gap-1"
    div class="lg:flex-grow"
      h1 class="page-title" = content_title

  = turbo_frame_tag @todo
    = render 'form', todo: @todo

app/views/todos/index.html.slim
- content_title = 'Todos'
- content_for :page_title, content_title

div class="w-full"
  div class="header lg:flex items-center gap-1"
    div class="lg:flex-grow center"
      h1 class="text-center lg:page-title" = content_title
    div class="lg:flex-shrink"
      = render 'todos/new_todo_link'

  div id="todos" data-controller="drag" data-drag-url-value=move_todo_path(':id')
    - @todos.each do |todo|
      div class="list-wrapper"
        = render todo

app/views/todos/new.html.slim
- content_title = 'New todo'
- content_for :page_title, "Todos | #{content_title}"

div class="w-full"
  div class="header lg:flex items-center gap-1"
    div class="lg:flex-grow"
      h1 class="page-title" = content_title
    div class="lg:flex-shrink"
      = link_to 'Back to todos', todos_path, class: 'button'

  = render 'form', todo: @todo

app/views/todos/show.html.slim
= render @todo

app/views/todos/update.turbo_stream.slim
= turbo_stream.replace @todo
= turbo_stream.update 'alerts', partial: 'application/notification', locals: { message: 'Todo updated.' }